### ISSUE TITLE
Better file preview page

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/LogManager#1]
Instead of just dumping the page for the user to make sense of it, parse it and order it in a DataTable, with three columns:
- level
- date
- content

Then you could:
- highlight each row with a different color depending on the level;
- filter only a certain level
- search

Got the idea from https://github.com/rap2hpoutre/laravel-log-viewer

**Comment by tabacitu** [comment]
This: https://github.com/jenssegers/laravel-raven
This is what it needs to look and work like.

**Comment by clarkewing** [comment]
The screenshot on the GitHub page doesn't point to anywhere. Is this what you were talking about?
https://sentry.io/_assets/screenshots/features-page-dash-e8a6fd442fa9d8785ddeb665ea8f55f9ca940de4d8b1d90517ae35e650a259c7.jpg

**Comment by lloy0076** [comment]
@tabacitu This sounds like someone should make a **separate** log view package?

**Comment by ShamarKellman** [comment]
I like this idea please see screenshot of my proposed idea.
Files view:
![snip2](https://user-images.githubusercontent.com/4120411/35332987-76ded2aa-00e3-11e8-9451-41865184c46b.PNG)

Preview: 
![snip1](https://user-images.githubusercontent.com/4120411/35333017-8c296f1c-00e3-11e8-81b1-45e9318a0dcd.PNG)
![snip3](https://user-images.githubusercontent.com/4120411/35333029-987ae8ea-00e3-11e8-87e7-223865bc17be.PNG)


Should be making a pull request within the next day or so.

**Comment by tabacitu** [comment]
@ShamarKellman that looks awesome, thank you.
@lloy0076 I agree - if we get to something that complicated it should probably be a separate package.
