### ISSUE TITLE
404 for admin/log

### ISSUE THREAD

**Issue by chef-it** [Laravel-Backpack/LogManager#10]
After adding through composer, adding the provider to config/app, and the link in sidebar.blade, it returns a 404 when clicking on the link.

Running on:
Laravel 5.4
Ubuntu 16.04
PHP 7.0.15

**Comment by tabacitu** [comment]
Hi @chef-it ,

Have you changed the admin prefix? If it's something different than "admin", you might need to change the link in ```sidebar.blade.php``` accordingly.

Cheers!
