### ISSUE TITLE
Cannot do any actions no matter preview, download or delete

### ISSUE THREAD

**Issue by swingywc** [Laravel-Backpack/LogManager#12]
Hi there, I have installed the following:
PHP 7.0.17
laravel Installer 1.3.5

My composer.json settings like below:

> {
>     "name": "laravel/laravel",
>     "description": "The Laravel Framework.",
>     "keywords": ["framework", "laravel"],
>     "license": "MIT",
>     "type": "project",
>     "require": {
>         "php": ">=5.6.4",
>         "backpack/backupmanager": "^1.1",
>         "backpack/base": "^0.7.16",
>         "backpack/crud": "^3.2",
>         "backpack/logmanager": "^2.3",
>         "laravel/framework": "5.4.*",
>         "laravel/tinker": "~1.0"
>     },
>     "require-dev": {
>         "backpack/generators": "^1.1",
>         "fzaninotto/faker": "~1.4",
>         "laracasts/generators": "dev-master as 1.1.4",
>         "mockery/mockery": "0.9.*",
>         "phpunit/phpunit": "~5.7"
>     },
>     "autoload": {
>         "classmap": [
>             "database"
>         ],
>         "psr-4": {
>             "App\\": "app/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "tests/"
>         }
>     },
>     "scripts": {
>         "post-root-package-install": [
>             "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "php artisan key:generate"
>         ],
>         "post-install-cmd": [
>             "Illuminate\\Foundation\\ComposerScripts::postInstall",
>             "php artisan optimize"
>         ],
>         "post-update-cmd": [
>             "Illuminate\\Foundation\\ComposerScripts::postUpdate",
>             "php artisan optimize"
>         ]
>     },
>     "config": {
>         "preferred-install": "dist",
>         "sort-packages": true
>     }
> }

I have just followed the instruction in README.md to install the logManager. However, I cannot access the file by any action like preview, download or delete.

While entering the preview action, it gives me this error:
`The requested resource /admin/log/preview/laravel.log was not found on this server.`
and for download action, it gives me this error:
`The requested resource /admin/log/download/laravel.log was not found on this server.`

Does anyone know how to solve it? Appreciate for any help.

**Comment by tabacitu** [comment]
Hi @swingywc ,

For the LogManager to be more useful, you should set ```APP_LOG=daily``` in your .ENV file. If you do that, does it work for the newly generated log files (dailies)?

Cheers!
