### ISSUE TITLE
Error: InvalidArgumentException in FilesystemManager.php line 121: Driver [] is not supported.

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/LogManager#13]
Got this error: 

`InvalidArgumentException in FilesystemManager.php line 121: Driver [] is not supported.`

Clean installation, laravel 5.4

Already executed the clear commands:

`composer dump-autoload`
`php artisan config:clear`
`php artisan clear-compiled`

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'region' => env('AWS_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ],

    ],
    //backpack
    'uploads' => [
                'driver' => 'local',
                'root' => public_path('uploads'),
            ],
    // used for Backpack/LogManager
    'storage' => [
                'driver' => 'local',
                'root'   => storage_path(),
            ],

**Comment by s7e-20** [comment]
Same here.

**Comment by dkwiebe** [comment]
I'm testing LogManager and am seeing the same issue.

**Comment by Heri88** [comment]
Anyone found a solution?

**Comment by tabacitu** [comment]
Guys... I'm sorry, no idea what's happening here. Cant't get the same error and it SEEMS like all drivers are specified - so I really don't understand it.

Have any of you found a solution yet?

Cheers!

**Comment by fahmianuar84** [comment]
Try to define your 'uploads' & 'storage' array into 'disks' : 
```
'disks' => [

    'local' => [
        'driver' => 'local',
        'root' => storage_path('app'),
    ],

    'public' => [
        'driver' => 'local',
        'root' => storage_path('app/public'),
        'url' => env('APP_URL').'/storage',
        'visibility' => 'public',
    ],
    //backpack
    'uploads' => [
                'driver' => 'local',
                'root' => public_path('uploads'),
            ],
    // used for Backpack/LogManager
    'storage' => [
                'driver' => 'local',
                'root'   => storage_path(),
            ],
    's3' => [
        'driver' => 's3',
        'key' => env('AWS_KEY'),
        'secret' => env('AWS_SECRET'),
        'region' => env('AWS_REGION'),
        'bucket' => env('AWS_BUCKET'),
    ],

],
```
Just like this example : https://github.com/Laravel-Backpack/Demo/blob/master/config/filesystems.php

**Comment by tabacitu** [comment]
:-)) @fahmianuar84 , very nice spotting of this small user error. Haste makes waste, I guess :-)

@eduardoarandah , @Top-Developer , @dkwiebe @Heri88 - make sure the disks you define are INSIDE the ```disks``` array, not outside it.

Very glad this issue is solved. Thank you again @fahmianuar84 .

Cheers!

**Comment by cvassios-ekko** [comment]
Getting the same issue, but my disks are defined inside the disks array

**Comment by sallmin** [comment]
Try running **php artisan config:clear** . I had the same issue

**Comment by kobacik** [comment]
@sallmin thanks salmin ^^ i really didn't think for this :))
