### ISSUE TITLE
Limit access to settings with middleware

### ISSUE THREAD

**Issue by OliverZiegler** [Laravel-Backpack/LogManager#14]
I think it would be nice to have the ability to limit access to the log routes.

Easiest way could be some config file where we can specify custom middleware to protect the route like provided in backpack base for elfinder.

Any opinions?

**Comment by tabacitu** [comment]
I think it's a great idea. 

Actually... I think this should work for all Backpack packages. They're all currently behind the ```['web', 'admin']``` middlewares. If they need to be changed, it's so so difficult right now. In a few days it will be a lot easier, if we allow developers to overwrite route files like this PR does https://github.com/Laravel-Backpack/LogManager/pull/18, but it could be even easier, if you had an option in the config file.

@OliverZiegler what do you think - would overwriting the route file be enough, or should we also add a config option? Would config + route be more helpful, or more confusing?

**Comment by OliverZiegler** [comment]
@tabacitu when we can easily overwrite the routes file I think a config option is obsolete.

**Comment by tabacitu** [comment]
Totally agree. Since we can easily overwrite routes now, let's close this. Cheers!
