### ISSUE TITLE
Undefined variable: logs

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/LogManager#23]
# Bug report

### What I did:
Installed Demo
opened log manager.

### What happened:
Undefined variable: logs (View: C:\xampp7\htdocs\backpack-demo\resources\views\vendor\backpack\logmanager\logs.blade.php)

**Comment by cerelli** [comment]
I just installed a new version and I noticed that logs.blade.php is not the same as the repository.

**Comment by cerelli** [comment]
Try to remove the logmanager views under ```resources\views\vendor\backpack...```
