### ISSUE TITLE
Undefined function backpack_middleware() after composer update

### ISSUE THREAD

**Issue by promatik** [Laravel-Backpack/LogManager#25]
# Bug report

### What I did:
After a composer update, `php artisan serve` doesn't work due to the error `Call to undefined function backpack_middleware()`.

### What happened:
```
In logmanager.php line 15:
Call to undefined function backpack_middleware()
```

### What I've already tried to fix it:
In the file `\vendor\backpack\logmanager\src\routes\backpacklogmanager.php`, changing the call to the function, `backpack_middleware()` back to the string `"admin"` solves the problem.

Apparently, helpers aren't loaded yet?

### Backpack, Laravel, PHP, DB version:
Latest Backpack 3.4.30
Latest Laravel 5.6.33
PHP 7.1.11
MySQL 5.7

**Comment by Lzxe92** [comment]
Have the same problem. No updates?

**Comment by promatik** [comment]
@Lzxe92 you can temporarily solve this by changing the file `\vendor\backpack\logmanager\src\routes\backpacklogmanager.php`, change the call to the function `backpack_middleware()` to the string `'admin'`:

    ...
    'middleware' => ['web', 'admin'],

**Comment by tabacitu** [comment]
@promatik - thanks a lot for the bug report. Finally been able to get this myself in a project - it doesn't always do this, and I have NO IDEA why sometimes routes are loaded _before_ helpers.

Anyway, I was able to test and confirm - I've just pushed a fix where we use the results of ```backpack_middleware()``` in the routes file, instead of the helper itself.

Thanks, bye!

**Comment by rudolphp** [comment]
This error still comes on composer update.

**Comment by tabacitu** [comment]
@rudolphp do you mean you can't run ```composer update```? Or that you can't load the pages after a ```composer update```? Both seem to work for me...

**Comment by rudolphp** [comment]
@tabacitu  - this error was coming when I ran "php artisan". But now the error has stopped. I don't know the root cause.

**Comment by tabacitu** [comment]
@rudolphp ok, thank you.
