### ISSUE TITLE
Logs have not been working for months "The payload is invalid."

### ISSUE THREAD

**Issue by 666lampshadesOG** [Laravel-Backpack/LogManager#30]
# Bug report

### What I did:

Tried following this answer but no luck: https://github.com/Laravel-Backpack/LogManager/issues/28#issuecomment-494299732  ( i have the correct blade files )

I get errors when I view the logs.

I deleted the logmanager folder and reinstalled with composer with the following settings

```
        "backpack/base": "^1.0",
        "backpack/crud": "^3.5",
        "backpack/logmanager": "^2.3",
```

### What I expected to happen:

I expected I could view my logs.

### What happened:

When I view log, I get error

domain.co/admin/log/preview/bGFyYXRlbC0yMEE5LTA4LTMxLmxvZw==

```
 Illuminate \ Contracts \ Encryption \ DecryptException
The payload is invalid.
```
```
vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php
```

```
        if (! $this->validPayload($payload)) {
            throw new DecryptException('The payload is invalid.');
        }
```

### What I've already tried to fix it:

Tried deleting the logmanager folder and reinstalling with composer.

Tried deleting all log files

### Backpack, Laravel, PHP, DB version:

```
"backpack/base": "^1.0",
"backpack/crud": "^3.5",
"backpack/logmanager": "^2.3",
"laravel/framework": "5.7.*",
"php": "^7.1.3",
```

**Comment by tabacitu** [comment]
Hi @666lampshadesOG ,

I think it's the same issue here https://github.com/Laravel-Backpack/LogManager/issues/28#issuecomment-494299732 - and the same solution should work for you: I suspect your have the LogManager blade files published in your ```resources/views/vendor/backpack/crud/logmanager``` folder. **Delete that folder if you haven't manually edited those files**.

Let me know if this doesn't fix it for you. I'm pretty sure it will.

Cheers!
