### ISSUE TITLE
Class 'Str' not found

### ISSUE THREAD

**Issue by mariovillani** [Laravel-Backpack/LogManager#43]
# Bug report

### What I did:
Trying to visualize a log file by Preview.

### What I expected to happen:
Visualize the log file
### What happened:
Error 500 has been thrown:

[2020-04-27 15:02:26] production.ERROR: Class 'Str' not found (View: /var/www/html/vendor/backpack/logmanager/src/resources/views/log_item.blade.php) {"exception":"[object] (ErrorException(code: 0): Class 'Str' not found (View: /var/www/html/vendor/backpack/logmanager/src/resources/views/log_item.blade.php) at /var/www/html/storage/framework/views/5dedba481f37beec496db43d81f8d62fa5f0d33b.php:26)

### What I've already tried to fix it:
Didn't try but somewhere (i think) should be added "use Illuminate\Support\Str;"

### Backpack, Laravel, PHP, DB version:
Backpack v4.0.60
PHP v.7.4.5
Laravel Framework v.7.8.1
Backpack LogManager v.3.0.5

**Comment by tabacitu** [comment]
Indeed - usually Str is aliased inside ```config/app.php```. Until we push a fix @MarioVillani please make sure to add these aliases there:
```php
    'aliases' => [
        // ...
        'Arr'       => Illuminate\Support\Arr::class,
        // ..
        'Str'       => Illuminate\Support\Str::class,
        // ..
    ],
```

I believe default Laravel installs have them by default. So I'm wondering - did you upgrade this project from a previous Laravel version? If so what version did you start at?

Cheers!

**Comment by mariovillani** [comment]
Yes, I upgraded from Laravel 5.6.* version. I just checked and the alias is missing. Thank you!

**Comment by tabacitu** [comment]
Glad to help!

**Comment by Polfo** [comment]
I had this `Class 'Str' not found ` issue on a project started on laravel 5.7.22 and now on 8.6.0
Adding the `aliases `in `config.app` solved the issue. A google search on `Class 'Str' not found laravel` pointed to this issue. So it did not take much time to fix. Thanks.
