### ISSUE TITLE
Function strftime() is deprecated

### ISSUE THREAD

**Issue by kunli0** [Laravel-Backpack/LogManager#54]
# Bug report

### What I did: 

View a log in Log Manager.

### What I expected to happen: 

See Log entries.

### What happened: 

Saw log entries, however emergency logger file is created also to due to deprecated function use.

### What I've already did to fix it: 

On line 39 of logs.blade.php changed formatLocalized('%d %B %Y') to isoFormat(config('backpack.base.default_date_format')) 

On line 40 of logs.blade.php changed formatLocalized('%H:%M') to isoFormat('HH:mm')

### Backpack, Laravel, PHP, DB version: 

5.0, 9.14, 8.1.2, Maria DB 10.6.7

**Comment by maurohmartinez** [comment]
Hi, @kunli0!
I can confirm that `formatLocalized()` was deprecated and I already submitted a [PR](https://github.com/Laravel-Backpack/LogManager/pull/55) to address this.
This will be closed once the PR is merged.

Thanks for reporting it!

**Comment by tabacitu** [comment]
Merged and tagged! Thanks @kunli0 !
