### ISSUE TITLE
Need to update instruction on readme as per v6

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/LogManager#64]
Need to update or add instructions for backpack v6👇❌
```
# [optional] Add a sidebar_content item for it
php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('log') }}'><i class='nav-icon la la-terminal'></i> Logs</a></li>"
```

The same changes are required on the **following DOCS page** and on **every repo's** readme too.
https://backpackforlaravel.com/docs/6.x/install-optionals

**Comment by tabacitu** [comment]
Good find @karandatwani92

**Comment by karandatwani92** [comment]
- [x] DOCS https://github.com/Laravel-Backpack/docs/pull/483
- [x] BackupManager https://github.com/Laravel-Backpack/BackupManager/pull/123
- [x] LogManager https://github.com/Laravel-Backpack/LogManager/pull/65
- [x] Settings https://github.com/Laravel-Backpack/Settings/pull/128
- [x] PageManager https://github.com/Laravel-Backpack/PageManager/pull/136
- [x] PermissionManager
- [x] MenuCrud https://github.com/Laravel-Backpack/MenuCRUD/pull/80
- [x] FileManager

**Comment by tabacitu** [comment]
Merged! Thanks @karandatwani92
